/*
 * generated by Xtext 2.12.0
 */
package uk.ac.york.cs.entities;

import uk.ac.york.cs.entities.AbstractEntityDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EntityDSLRuntimeModule extends AbstractEntityDSLRuntimeModule {
}
