/*
 * generated by Xtext 2.12.0
 */
package uk.ac.york.cs.entities;

import uk.ac.york.cs.entities.EntityDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EntityDSLStandaloneSetup extends EntityDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new EntityDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
