/**
 * generated by Xtext
 */
package uk.ac.york.cs.statemachines.serializer;

import uk.ac.york.cs.statemachines.serializer.AbstractStatesSemanticSequencer;

@SuppressWarnings("all")
public class StatesSemanticSequencer extends AbstractStatesSemanticSequencer {
}
