/**
 * generated by Xtext
 */
package uk.ac.york.cs.statemachines.serializer;

import uk.ac.york.cs.statemachines.serializer.AbstractStatesSyntacticSequencer;

@SuppressWarnings("all")
public class StatesSyntacticSequencer extends AbstractStatesSyntacticSequencer {
}
