/*
 * generated by Xtext
 */
package uk.ac.york.cs.statemachines;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class StatesRuntimeModule extends uk.ac.york.cs.statemachines.AbstractStatesRuntimeModule {

}
