/*
 * generated by Xtext 2.12.0
 */
package uk.ac.york.cs.entities.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EntityDSLUiModule extends AbstractEntityDSLUiModule {

	public EntityDSLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
