/*
 * generated by Xtext 2.14.0
 */
package uk.ac.york.cs.entities.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EntityDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("uk/ac/york/cs/entities/parser/antlr/internal/InternalEntityDSL.tokens");
	}
}
