/*
 * generated by Xtext 2.14.0
 */
package uk.ac.york.cs.entities.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.york.cs.entities.parser.antlr.internal.InternalEntityDSLParser;
import uk.ac.york.cs.entities.services.EntityDSLGrammarAccess;

public class EntityDSLParser extends AbstractAntlrParser {

	@Inject
	private EntityDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEntityDSLParser createParser(XtextTokenStream stream) {
		return new InternalEntityDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public EntityDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EntityDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
