/*
 * generated by Xtext 2.12.0
 */
package uk.ac.york.cs.entities.ide;

import uk.ac.york.cs.entities.EntityDSLRuntimeModule;
import uk.ac.york.cs.entities.EntityDSLStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EntityDSLIdeSetup extends EntityDSLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EntityDSLRuntimeModule(), new EntityDSLIdeModule()));
	}
	
}
