/*
 * generated by Xtext
 */
package uk.ac.york.cs.statemachines.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import uk.ac.york.cs.statemachines.ui.internal.StatesActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class StatesExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return StatesActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return StatesActivator.getInstance().getInjector(StatesActivator.UK_AC_YORK_CS_STATEMACHINES_STATES);
	}
	
}
