/*
 * generated by Xtext
 */
package uk.ac.york.cs.statemachines.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class StatesAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("uk/ac/york/cs/statemachines/parser/antlr/internal/InternalStates.tokens");
	}
}
