/*
 * generated by Xtext
 */
package uk.ac.york.cs.statemachines.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.york.cs.statemachines.services.StatesGrammarAccess;

public class StatesParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private StatesGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected uk.ac.york.cs.statemachines.parser.antlr.internal.InternalStatesParser createParser(XtextTokenStream stream) {
		return new uk.ac.york.cs.statemachines.parser.antlr.internal.InternalStatesParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "StateMachine";
	}
	
	public StatesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(StatesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
