/*
 * generated by Xtext 2.12.0
 */
package uk.ac.york.cs.entities.validation;

import uk.ac.york.cs.entities.validation.AbstractEntityDSLValidator;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class EntityDSLValidator extends AbstractEntityDSLValidator {
	
//	public static final INVALID_NAME = 'invalidName'
//
//	@Check
//	public void checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.getName().charAt(0))) {
//			warning("Name should start with a capital",
//					EntityDSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME);
//		}
//	}
	
}
