/*
 * generated by Xtext
 */
package uk.ac.york.cs.statemachines.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class StatesUiModule extends uk.ac.york.cs.statemachines.ui.AbstractStatesUiModule {
	public StatesUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
