/*
 * generated by Xtext 2.14.0
 */
package uk.ac.york.cs.entities.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEntityDSLScopeProvider extends DelegatingScopeProvider {
}
